### ISSUE TITLE
ur5_gazebo_joint_position_control.launch  - launch-file is missing?

### ISSUE THREAD

**Issue by ProfJust** [dairal/ur5-tcp-position-control#2]
Trying to work with your  tutorial, I cannot find the **ur5_gazebo_joint_position_control.launch** - File  which is called by 
`$ roslaunch ur5-tcp-position-control ur5_gazebo_joint_position_control.launch`

Could you please add this file or tell me where I can find it. 
Thank you very much..

**Comment by ProfJust** [comment]
Found the file is in this  [package ](https://github.com/dairal/ur5-joint-position-control/blob/main/launch/ur5_joint_position_control.launch)
https://github.com/dairal/ur5-joint-position-control/blob/main/launch/ur5_joint_position_control.launch

So just change the call of the launch-file within the tutorial from
$ roslaunch ur5-tcp-position-control ur5_gazebo_joint_position_control.launch  to ... 
```
>$ roslaunch ur5- ur5_gazebo_joint_position_control.launch
ur5-joint-position-control  ur5-tcp-position-control
```

**Comment by dairal** [comment]
Thank you for investigating this.
You are absolutely right, I just changed it in the tutorial.
